import { useEffect, useState } from 'react'
import { ArrowLeft, ExternalLink, Image, Save, Store } from 'lucide-react'
import { actualizarTienda, getTienda } from '../services/apiAdmin'
import { PUBLIC_URL } from '../config/env'
import { currency } from '../utils/formatters'

export default function StorePage() {
  const [data, setData] = useState(null)
  const [form, setForm] = useState({ nombre: '', descripcion: '', direccion: '', whatsapp: '', logoUrl: '' })
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [saving, setSaving] = useState(false)
  useEffect(() => { getTienda().then((result) => { setData(result); setForm({ nombre: result.negocio.nombre || '', descripcion: result.negocio.descripcion || '', direccion: result.negocio.direccion || '', whatsapp: result.negocio.whatsapp || '', logoUrl: result.negocio.logo_url || '' }) }).catch((err) => setError(err.message)) }, [])
  const update = (key, value) => setForm({ ...form, [key]: value })
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const result = await actualizarTienda(form); setData({ ...data, negocio: result.negocio }); setMessage('Cambios guardados correctamente') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const business = data?.negocio
  return <section className="content store-content"><div className="store-heading"><div><h2>Mi Tienda Online</h2><p>Personaliza y publica la página de {business?.nombre || 'tu negocio'}.</p></div><div className="store-actions"><a className="store-link" href={`${PUBLIC_URL}/perfil`}><ArrowLeft size={14} />Volver a comprar</a><a className="store-link" href={PUBLIC_URL} target="_blank" rel="noreferrer"><ExternalLink size={14} />Ver en vivo</a></div></div>{error && <div className="alert">{error}</div>}{message && <div className="success-message">{message}</div>}<div className="store-layout"><form className="store-editor" onSubmit={save}><div className="store-tabs"><span className="active"><Store size={14} />Contenido</span><span>Secciones</span><span>Compartir</span></div><label>Nombre del negocio<input value={form.nombre} onChange={(event) => update('nombre', event.target.value)} required /></label><label>Descripción<input value={form.descripcion} onChange={(event) => update('descripcion', event.target.value)} placeholder="Describe tu negocio" required /></label><label>WhatsApp<input value={form.whatsapp} onChange={(event) => update('whatsapp', event.target.value)} required /></label><label>Dirección<input value={form.direccion} onChange={(event) => update('direccion', event.target.value)} required /></label><label>URL del logo<input type="url" value={form.logoUrl} onChange={(event) => update('logoUrl', event.target.value)} placeholder="https://..." /></label><button className="save-store" disabled={saving}><Save size={15} />{saving ? 'Guardando...' : 'Guardar cambios'}</button></form><section className="store-preview"><div className="preview-label"><span>Vista previa</span><div><button className="device-active">Móvil</button><button>Escritorio</button></div></div><div className="phone-frame"><div className="phone-top"><b>{form.nombre || 'Mi negocio'}</b><a href={`${PUBLIC_URL}/perfil`}>Comprar</a></div><div className="phone-hero"><span>¡Bienvenido!</span><h3>{form.nombre || 'Mi negocio'}</h3><p>{form.descripcion || 'Los mejores productos para ti'}</p><a href={PUBLIC_URL}>Ver catálogo</a></div><h4>Mis productos</h4><div className="phone-products">{(data?.productos || []).slice(0, 3).map((product) => <article key={product.pk_id}><div>{product.imagen_url ? <img src={product.imagen_url} alt="" /> : <Image size={20} />}</div><b>{product.nombre}</b><small>{currency.format(product.precio)}</small></article>)}</div><div className="phone-contact"><span>¿Tienes preguntas?</span><a href={`https://wa.me/${form.whatsapp}`}>Escribir</a></div></div></section></div></section>
}
